### ISSUE TITLE
Support Conformance test authoring.

### ISSUE THREAD

**Issue by n3wscott** [knative-sandbox/reconciler-test#100]
Need an example conformance test documented for downstreams to reference.

There are a few features we still need that block downstreams from really using the framework for creating conformance test authoring and running:

- reporting results.
- https://github.com/knative-sandbox/reconciler-test/issues/65
- https://github.com/knative-sandbox/reconciler-test/issues/64
- https://github.com/knative/serving/issues/6264

Add others as they are found.

**Comment by slinkydeveloper** [comment]
How about these:

* https://github.com/knative/eventing/tree/main/test/rekt/features/broker
* https://github.com/knative/eventing/blob/main/test/rekt/broker_test.go

**Comment by vaikas** [comment]
@slinkydeveloper @n3wscott Couple of things based off these samples that came to mind from a quick look:
1. mtchannelbroker is hardcoded, so what is the recommended way to pass in a different BrokerClass (say, Kakfa)? Or just pass in an already created Broker (by ref? Name?) instead of creating a broker in the test?
2. I don't see an easy way to test mutations. We have install, but I don't see a way to modify a resource. For example, I'd like to author a test that says: Create MTChannelBasedBroker, then try to change it.

**Comment by n3wscott** [comment]
1. The test for broker conformance is written incorrectly. We need to pass a ref to the broker under test and create the broker external to the conformance run.
2. The outer wrapper is intended to be copied into the target repo and mutated there, with customizations specific to the test env the rest of the tests need not be aware of. 

We are not quite there, I think we can get there in a week.
