### ISSUE TITLE
Test execution model

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/reconciler-test#106]
Today we have this code https://github.com/knative-sandbox/reconciler-test/blob/master/pkg/environment/magic.go where we take the various user `StepFn`s and execute them.

This model has several problems:

* We don't really implement `Requirement` as we would love to: if a `Requirement` fails, we don't want the test to fail, but we want to skip the asserts (don't execute them at all) and just run the teardown. More generally, we cannot really control what to do after a StepFn fails or succeds, which is preferable given our APIs and the meanings of our "phases".
* Test branching `RunTest` is allowed but it doesn't really makes sense to do so, and in setup, teardown and requirement phases it doesn't work properly.
* Context is not properly handled per `StepFn` (I attempted to fix it here https://github.com/knative-sandbox/reconciler-test/pull/96)
* Test phases execution is enforced through running all the phases in the same subtest (as implemented by me in https://github.com/knative-sandbox/reconciler-test/pull/52), but this solution breaks subtests, panic catching, cleanup, skipping and deadline features of `*testing.T`
* How `MustNot` and `ShouldNot` be implemented? The user should assert the original or negated assertion?

I attempted to fix it by reimplementing part of the job of `go test` in this PR https://github.com/knative-sandbox/reconciler-test/pull/97 but there are several issues in it, most notably the fact that I'm reimplementing `go test` :smile: 

cc @dprotaso @n3wscott do you have any viable solutions to fix the above issues?

**Comment by dprotaso** [comment]
The other notable thing I realized today is `go test ./...` (when testing multiple packages) actually runs the test binaries in parallel.

so `go test pkgA/e2e pkgA/e2e/scale` will immediately spin up two processes. The # of processes is cpu count dependent.

There's actually a poorly documented flag that limits this parallelism `-p 1`. See: https://golang.org/cmd/go/#hdr-Compile_packages_and_dependencies

**Comment by slinkydeveloper** [comment]
@dprotaso running parallel test binaries is not a big problem at the end of the day, it's better than running in parallel in the same process, which makes the whole execution model for us more complicated

**Comment by dprotaso** [comment]
@slinkydeveloper I agree. I mentioned it since I'm poking at improving serving's e2e scripts.

The other notable thing I realize is that test timeouts panic so all the tear-downs/cleanup do not run. I think the only way to work around this is to wrap the test binary in a separate process in `-exec`. I'm looking into that now

**Comment by slinkydeveloper** [comment]
Are you thinking to run features teardown phases in there?

**Comment by dprotaso** [comment]
I'm just looking to clean up serving's bash scripts and thinking this approach would work to replace things like toggling features on the cluster

https://github.com/knative/serving/blob/17e40b1c4c0e28eef577fc80e67df6bf9406e7b2/test/e2e-tests.sh#L111-L117

I'm unsure how to wrangle features setup/teardown with this

**Comment by slinkydeveloper** [comment]
I'll try to take a crack at it serializing all the features executions... Not the more elegant approach, but it could be a good start

**Comment by slinkydeveloper** [comment]
@n3wscott can you check again the points of this issue and see if there's something else in your opinion we need to tackle?

**Comment by n3wscott** [comment]
> * We don't really implement `Requirement` as we would love to: if a `Requirement` fails, we don't want the test to fail, but we want to skip the asserts (don't execute them at all) and just run the teardown. More generally, we cannot really control what to do after a StepFn fails or succeds, which is preferable given our APIs and the meanings of our "phases".

I am not sure this is true, requirement is a way to fast fail without wasting time on the setup and assert phases.

> * Test branching `RunTest` is allowed but it doesn't really makes sense to do so, and in setup, teardown and requirement phases it doesn't work properly.

I think this is fixed.

* Context is not properly handled per `StepFn` (I attempted to fix it here https://github.com/knative-sandbox/reconciler-test/pull/96)

I am not sure what this means. But I think were we end up is ok.

> * Test phases execution is enforced through running all the phases in the same subtest (as implemented by me in https://github.com/knative-sandbox/reconciler-test/pull/52), but this solution breaks subtests, panic catching, cleanup, skipping and deadline features of `*testing.T`

I think we are good now.

> * How `MustNot` and `ShouldNot` be implemented? The user should assert the original or negated assertion?

They should be the same as `Must` and `Should`, no special treatment except for I can run just the `ShouldNot` level of tests if I wish.

**Comment by slinkydeveloper** [comment]
Link to #124, that panic is suspect...

**Comment by slinkydeveloper** [comment]
> I am not sure this is true, requirement is a way to fast fail without wasting time on the setup and assert phases.

As is now (with #112), the test is skipped but not failed. Maybe this should be configurable somehow?

**Comment by slinkydeveloper** [comment]
Related #142

**Comment by mgencur** [comment]
Hello! 
Looking at the docs and the discussion above, and also the discussions in https://github.com/knative-sandbox/reconciler-test/issues/51 the `Requirements` phase is still kind of confusing to me. The way it is implemented now where the Requirements stage runs after Setup makes little sense, IMO.
The docs make it a little confusing too because on this line https://github.com/knative-sandbox/reconciler-test/blame/main/README.md#L167 it's used before Setup and a few lines after that it's used after Setup. But in reality, both these steps run after Setup: https://github.com/knative-sandbox/reconciler-test/blob/main/pkg/environment/magic.go#L245
If the purpose of the Requirements stage is to verify something in the environment that was not done in Setup then I think this stage should be executed before Setup. This would make it clear it's there to verify the environment before I do my own setup in the test. And I think it's been the main source of confusion about this stage. 
If the purpose is to verify something that was done in Setup then I think this whole stage is redundant. The Setup phase in itself is supposed do some "setup" and make sure the stuff is setup properly before running the actual tests or the test fails.
IMO, this phase should NOT be used in both cases because that will confuse people (like in my case).

Side note: If the requirements are not met then I think the test should fail and not be skipped. Skipped tests are often ignored because they're usually skipped on purpose - by implementing the skip in the test itself. But in this case we didn't give the test any signal to be skipped. Not meeting the requirements means abnormal conditions and test and/or setup should be fixed ASAP.

**Comment by mgencur** [comment]
Think another source of confusion is using Setup for both preparing the tests and executing some commands against the target SUT (system under test).
This probably comes from the fact that people know the well-known paradigms 
Given-When-Then (or Setup-Exercise-Verify or Arrange-Act-Assert). Then they come to
use this framework and suddenly wonder where the "Exercise/When/Act" phase is executed,
where they should place it. I'm wondering about it too.
It looks like the current framework allows for doing that partially in Setup and partially
in Assert but it's not clear what is preferred. Especially if assert is supposed to do assertions
and not actual actions against the system.
IMO, it would be useful to introduce one more step in the builder pattern.
So, this code:
```
f.Stable("Conformance").
  Should("Broker objects SHOULD include a Ready condition in their status",
    brokerHasReadyInConditions). // here the brokerHasReadyInConditions actually executes an action and then verifies conditions
```
would be replaced with:
```
f.Stable("Conformance").
    Act("Do actions that will result in something that is assertable", doMyAction).
    Should("Broker objects SHOULD include a Ready condition in their status",
      brokerHasReadyInConditions).
```
This brings it closer to the common understanding of the BDD style tests but it still gives an option to do a common Setup earlier that will be common to all variants.

**Comment by slinkydeveloper** [comment]
> This probably comes from the fact that people know the well-known paradigms
Given-When-Then (or Setup-Exercise-Verify or Arrange-Act-Assert). Then they come to
use this framework and suddenly wonder where the "Exercise/When/Act" phase is executed,
where they should place it. I'm wondering about it too.

Same feeling here. Given-when-then is a very simple paradigm well understood.

* Given: setup broker, subscription, receiver etc
* When: Send event
* Then: assert event received
